### ISSUE TITLE
checkQueues can lead to redis waiting queue full error

### ISSUE THREAD

**Issue by mcweba** [swisspost/vertx-redisques#170]
In the method [checkQueues()](https://github.com/swisspost/vertx-redisques/blob/b81ae0b0173e9134bfb5ae150e66b2cd04f96973/src/main/java/org/swisspush/redisques/RedisQues.java#L861) of the class _RedisQues_ we first get a list of all the queue names.

Then we iterate (in a for-loop) over all queue names and call _exists_ on the _redisAPI_. This for-loop does not bother whether _redisAPI_ has enough resources (waiting queue) and therefore errors like this are logged:

```
2024-04-24 13:28:41,019 ${sys:ch.post.it.host} dev  crush ERROR RedisQues - RedisQues is unable to check existence of queue my_fancy_queue_123
io.vertx.core.impl.NoStackTraceThrowable: Redis waiting queue is full
```
We need a way to _backpressure_ these calls to not exhaust the redis waiting queue. Filling the redis waiting queue with the code mentioned above also has affects to other places where redis is used and can lead there to problems.

All the places where over all queues is iterated must be checked!

According to the logs this also happens here [QueueStatisticsCollector.updateStatisticsInRedis(String queueName)](https://github.com/swisspost/vertx-redisques/blob/b81ae0b0173e9134bfb5ae150e66b2cd04f96973/src/main/java/org/swisspush/redisques/util/QueueStatisticsCollector.java#L298)

**Comment by mcweba** [comment]
@hiddenalpha thank you for taking the issue :-)

**Comment by hiddenalpha** [comment]
Handle in internal issue tracker is SDCISA-15771
